/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: J1G4R (https://sketchfab.com/jigar6102021)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/curious-skeleton-757d9863b3504a75a439b2b99a530454
Title: Curious skeleton
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";
import skeleton from '/3D/curious_skeleton.glb'
const Skeleton = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(skeleton);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["idle"].play();
  },[actions]);

  return (
    
      <group ref={group} {...props} dispose={null}>
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="root">
              <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <group name="RootNode0_0" scale={0.01}>
                  <group name="skeletal3_3">
                    <group name="GLTF_created_0">
                      <primitive object={nodes.GLTF_created_0_rootJoint} />
                      <skinnedMesh
                        name="Object_118"
                        geometry={nodes.Object_118.geometry}
                        material={materials.material_0}
                        skeleton={nodes.Object_118.skeleton}
                      />
                      <group name="skeleton2_2_correction">
                        <group name="skeleton2_2" />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
  );
};

useGLTF.preload(skeleton);
export default Skeleton;
